### ISSUE TITLE
[Page] Sign and Submit: Integrate backend, Enable submission after requirements met

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#1008]
Todo:

- [x] Inquire the backend about the endpoint with the confirmation id
- [x] Enable the final checkbox and submit -- once all the other checkboxes above have been checked
- [x] Show success box with confirmation number

**Comment by billhimmelsbach** [comment]
We'll be releasing this one after the bug bash next Thursday (November 7th 2024)
