### ISSUE TITLE
[Task] [Institutional Details] Get clarification on some backend institutional details API responses

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/sbl-frontend#137]
Hey @lchen-2101, I had a few super minor questions pop up when I was working on the institutional details page for the demo.

1. The sbl_institution_type and hmda_institution_types sometimes have punctuation at the end of their name values in the db seed data, which might be a mistake?
![Screenshot 2024-01-04 at 3 39 21 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/aea559b5-4117-477f-abb0-39b0ad1a2ffb)
![Screenshot 2024-01-04 at 3 48 56 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/c2a7a6cb-6d37-4263-a7d2-ffe0fd3a3481)

2. I see that there's both `hq_address_state_code` and 
```
"hq_address_state": {
  "code": "GA",
  "name": "Georgia"
},
```
in the "Get Institution" endpoint now. Can we just consolidate on one?
![Screenshot 2024-01-04 at 3 38 48 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/19b9194a-4bae-4bd9-bd75-762e332fdd24)

**Comment by billhimmelsbach** [comment]
Heyo @lchen-2101! I was just going through and closing my old tickets, and I double-checked on this one. I had a question about the `Other` option in `sbl_institution_types`. We talked about the need for the `Other` option to support a user inputting their own institution type after selecting this option, and I think [it was worked on](https://github.com/cfpb/regtech-user-fi-management/blob/main/src/entities/models/dto.py#L105C7-L105C35), but in [the seed data](https://github.com/cfpb/regtech-user-fi-management/blob/main/db_revisions/versions/a41281b1e109_seed_sbl_institution_type_table.py#L31), it looks like it's just represented as type `Other`. Could we fix that? I just want to test everything out before I close the book a bit on the shared lending platform.

**Comment by meissadia** [comment]
> Heyo @lchen-2101! I was just going through and closing my old tickets, and I double-checked on this one. I had a question about the `Other` option in `sbl_institution_types`. We talked about the need for the `Other` option to support a user inputting their own institution type after selecting this option, and I think [it was worked on](https://github.com/cfpb/regtech-user-fi-management/blob/main/src/entities/models/dto.py#L105C7-L105C35), but in [the seed data](https://github.com/cfpb/regtech-user-fi-management/blob/main/db_revisions/versions/a41281b1e109_seed_sbl_institution_type_table.py#L31), it looks like it's just represented as type `Other`. Could we fix that? I just want to test everything out before I close the book a bit on the shared lending platform.

I'm also trying to nail down the structure of `sbl_institution_types`. 
- Should the object in this example have an `sbl_type` property?
- Is `sbl_type` optional on these objects?

**Comment by billhimmelsbach** [comment]
Archiving this old issue, since we've solved issues around institution types.
