### ISSUE TITLE
[Breadcrumb] Combine the current CrumbTrails with react-router

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#168]
Can let the CrumbTrail auto-generate based on the `location.pathname` (e.g. `/profile-form/users/2349023`)

Follow-up to https://github.com/cfpb/sbl-frontend/pull/152#discussion_r1448145280

**Comment by billhimmelsbach** [comment]
Did you still want to pursue this one or is the current system we have good enough?
