### ISSUE TITLE
[Content Review] SBL "404 - Not found" & "500 - Error pages"

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#178]
These pages are clones of pages shown on CF.gov. 
 
We are looking for feedback on if the page language still fits within the context of the SBL app. 
 
✅  The 500 page clearly needs some rewording. I will take a crack at that tomorrow (1/18).

Length restrictions:
  - Don't go past 2 lines of text @ desktop width

## 404 - Not found
<img width="1257" alt="Screenshot 2024-01-19 at 3 39 37 PM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/9b27beba-6260-4679-b1d3-4e543d57ec55">

## 500 - Error
<img width="1256" alt="Screenshot 2024-01-19 at 3 41 24 PM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/c09aed12-5889-4c79-b58b-8af8dab8aeed">

**Comment by meissadia** [comment]
# 404 - Page not found
I think most of the current text fits.  I would remove the bit about "helpful tools" since we do not yet have any of those for SBL
 
"We can’t find the page you’re looking for. Visit our homepage for helpful resources, or contact us and we’ll point you in the right direction."

# 500 - Server error
"We are currently experiencing system issues, please try again at a later time."
 
Then for the `Contact` bit below the button: "Has this error persisted? Contact our support staff"

**Comment by natalia-fitzgerald** [comment]
Text updates: 
**404: We can't find the page you're looking for** 
Visit the platform homepage for additional resources or contact our support staff.

**500: Server error** 
We have encountered an error. Visit the platform homepage for additional resources or contact our support staff.

For each of these errors what is the preferred next step we'd like a user to take? The reason I ask is that for both we are visually prioritizing the return to the platform home (unauthenticated - I assume?) and I want to be sure that this is intentional. If contacting the support staff is the priority we will need to adjust this design hierarchy.

**Comment by meissadia** [comment]
@natalia-fitzgerald 
 
For the `404 Not found` page I do think we want to send users back to Unauthenticated landing page.  404 means they've landed at an unexpected location on our site and, assuming that WE weren't the ones that sent them there (i.e. a broken link), HOME seems like the most sensible place to direct them so that they can have a fresh start. 

For the `500 server error` page - this will be where users are directed when we run into an issue communicating with the API.  Hoping it was a one-off error, I think we should direct the user *back to the page that generated the error* so that they can try to load their data again.  If the failure is persistent then I would want the user to reach out to the support team, but that would require tracking how many times an error has occurred and dynamically adjusting the `500` page in response.

**Comment by dan-padgett** [comment]
I like the proposed phrasing for the 404. A slight concern is whether the user is going to interpret "platform homepage" as the authenticated page or the unauthenticated page. Unfortunately I can't think of an alternate that would more clearly set expectations for where the button would take them. (Same concern holds for the 500 error as well.)

With the 500 error, in this context does "one-off" mean that they should be able to retry/refresh and have things work properly? If so, I like the original suggestion to try again. And if that doesn't work, the homepage button and support staff link seem to give good secondary and tertiary options.

**Comment by sthomas93** [comment]
@chynnakeys @cdorney25 We agree with the language that Meissa provided above. @natalia-fitzgerald

**Comment by meissadia** [comment]
@dan-padgett Yes, your interpretation of "one-off" matches mine.
