### ISSUE TITLE
[Task] Loading/Error States - User Profile Submission

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#182]
Added states to be shown:
- Styling during loading (e.g. button disabled, spinner)
- Styling during an error (e.g. AlertFieldLevel with error message in red text below the button)

Potential UX:
- After a failed submission, disable the button for 5 seconds.

**Comment by billhimmelsbach** [comment]
I think this one has been completed, and we're not currently going to throttle people's API calls / disable the button? So maybe this one is good to close?
