### ISSUE TITLE
Consolidated list of design updates (shared platform)

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-frontend#188]
The purpose of this issue is to have a place to post design adjustments or changes to the shared platform pages.

**Comment by natalia-fitzgerald** [comment]
Upon reviewing the Shared platform (authenticated) page versus the View your user profile (in code) I noticed a _consistency_ in the status label (institution-list). This is the right way to do this. Unfortunately, the weight of the status label was inconsistent in my Figma file (500 in the authenticated page and 400 in the view user profile page). 

### Figma mock-up
| Authenticated page | View user profile |  
|------------| ------------|
|<img width="815" alt="Screenshot 2024-01-18 at 9 48 14 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/55bbfc90-748e-4922-8e8a-19770e878b9a">|<img width="955" alt="Screenshot 2024-01-18 at 9 50 38 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/8a67824f-e481-4d65-a065-50f3821e3166">|

### Code implementation
| Authenticated page | View user profile |  
|------------| ------------|
|<img width="815" alt="Screenshot 2024-01-18 at 9 48 14 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/21828fae-075b-40d0-8b80-4586b72beeb3">|<img width="868" alt="Screenshot 2024-01-18 at 9 48 04 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/3739c2c4-4ca6-4eb6-8104-960c5ad98e7f">|

My concern with the current implementation is that on the "View your user profile" page the heading (Associated financial institutions) and the status label look too close in styling. Since we definitely should have a consistent approach I'm thinking that it would be best to go with the 400 weight approach.

### Proposed update
- 400 weight for "Approved"status label


| Authenticated page | View user profile |  
|------------| ------------|
|<img width="955" alt="Screenshot 2024-01-18 at 9 50 38 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/f616148e-02df-4920-a962-12e381a4e7c7">|<img width="813" alt="Screenshot 2024-01-18 at 9 50 11 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/0397c870-69d4-4f2c-b87f-9405d9796811">|

**Comment by natalia-fitzgerald** [comment]
### Numbered icon list
There is a spacing adjustment I would like to make to the shared landing (unauthenticated) page. In the current implementation the space between the heading and the numbered icon list is 15px. The space between the list items is 30px. This creates a spacing association between the heading and the first list item.  

There are two options for how to address this issue: 

### Option 1: Increase the spacing
- Increase space between the heading and the list items to 30px
- (Possibly) also increase the space between the button and the heading to 60px 

| Implemented based on Figma | 45 before / 30 after | 60 before / 30 after |
|------------| ------------|------------|
|<img width="911" alt="Screenshot 2024-01-18 at 10 26 10 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/95b5ff9d-bdc5-4eb7-9536-fee6f9fa822e">|<img width="1343" alt="Screenshot 2024-01-18 at 10 37 55 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/ba5f292f-ae79-422e-9a0b-bad888361fd8">|<img width="1300" alt="Screenshot 2024-01-18 at 10 37 32 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/17601513-9db1-4000-8971-bc890d6db382">|

### Option 2: Add a divider line between the button and the numbered icon list 
- Add a divider with 45px above and below between the button and the numbered icon list
- Increase space between the heading and the list items to 30px

| Authenticated page | View user profile |  
|------------| ------------|
|<img width="911" alt="Screenshot 2024-01-18 at 10 26 10 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/95b5ff9d-bdc5-4eb7-9536-fee6f9fa822e">|<img width="889" alt="Screenshot 2024-01-18 at 9 26 15 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/b6547371-22af-4c5f-a9e0-f691e3eee359">

I'm partial to option 2 but welcome the the team's thoughts.

**Comment by billhimmelsbach** [comment]
> Option 2: Add a divider line between the button and the numbered icon list

I prefer option #2 for sure. I do think it would be nice to have a dividing line there to separate those concerns out a bit. Can we ticket that one?

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
I have reviewed the items listed on this issue and I believe they are all completed. So, I am closing this issue.
