### ISSUE TITLE
[Design] Error states for failed API calls

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#208]
Working to determine the best approach for displaying failed API calls when fetching data.

See the [original thread](https://github.com/cfpb/sbl-frontend/pull/171#issuecomment-1901724082) for additional context.

### Top of the content area
| Authenticated landing page | View your user profile |
|------------|------------|
![Group 378](https://github.com/cfpb/sbl-frontend/assets/77348967/7456cd92-61b6-4ee6-a40c-937055ce1f25)|![MVP_ View your user profile (error loading financial institution details) - v1](https://github.com/cfpb/sbl-frontend/assets/77348967/361375eb-6bd6-4b20-ade1-f3a1a0099f46)|

### Specific page location
| Authenticated landing page | View your user profile |
|------------|------------|
|![MVP_ Shared platform (authenticated) - error state v2](https://github.com/cfpb/sbl-frontend/assets/77348967/4eca4c69-926c-49e1-864d-7f8fc9e87bb8)|![MVP_ View your user profile (error loading financial institution details) - v2](https://github.com/cfpb/sbl-frontend/assets/77348967/e3ad38ae-4341-4ab9-beb7-edfab4b78ef2)|

If we want to provide further details we can include body copy in the alert. 
<img width="759" alt="Screenshot 2024-01-19 at 10 20 07 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/a3b31ccf-0a18-4dea-87cd-e869089df43a">

**Comment by billhimmelsbach** [comment]
Completed by #171
