### ISSUE TITLE
[Cypress] Resolve constantly failing E2E tests

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#210]
I'm tired of the Github error notifications...

**Comment by billhimmelsbach** [comment]
Thought I was getting close here: https://github.com/cfpb/sbl-frontend/pull/83

We had it as a possible goal for this sprint, but we can definitely take a stab at it next sprint.

**Comment by meissadia** [comment]
@billhimmelsbach Would you be okay with removing `@testing-library/cypress` for now?  That is the main blocker here and, while it would be nice to have the commands we use in Cypress mirror what we use in Jest, does not seem crucial to our ability to implement Cypress tests.

**Comment by billhimmelsbach** [comment]
Totally reasonable @meissadia. If you could do me a favor, and just dig a little into the commit that first caused these issues?

https://github.com/cfpb/sbl-frontend/pull/63

![Screenshot 2024-02-02 at 6 49 45 AM](https://github.com/cfpb/sbl-frontend/assets/19983248/2e3df9ff-9c96-4d71-99b2-07b004844cc1)

Before this commit was merged, it looks like cypress was working. I see there was an attempt to fix it by updating cypress and testing-library/cypress maybe that didn't work and then was merged anyway with a failing test?

Give it only like 30mins of investigation, and if not, we can pull @testing-library/cypress
