### ISSUE TITLE
[Component][Salesforce] Add a financial institution

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#218]
Will be used in the Salesforce forms - Complete your User Profile, Update your User Profile

<img width="750" alt="Screenshot 2024-02-01 at 2 16 50 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/c5e35f1e-f79e-4f9a-96e4-bb61757fb467">

**Comment by billhimmelsbach** [comment]
I think this is completed @shindigira

**Comment by billhimmelsbach** [comment]
We removed this for beta, but then also if we want to resurrect it later, it's a duplicate of #596
