### ISSUE TITLE
[Task] Replace Dropdown with Select

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#255]
This should be a pre-task to https://github.com/cfpb/design-system-react/issues/299
- Dropdown used in [sbl-frontend](https://github.com/cfpb/sbl-frontend/blob/main/src/pages/ProfileForm/Step1Form/Step1FormDropdownContainer.tsx#L3)
- Who else is using DSR? We should notify them of this deletion prior to implementing it.

**Comment by billhimmelsbach** [comment]
We currently don't need this since we've moved away from using the Select in the designs.
