### ISSUE TITLE
[Design Review] Complete Your User Profile (No Associations)

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#310]
- [x] Update to Figma text - Text Intro and Section Intro
- [ ] (pending) 8 or 10px underneath email address
- [x] period before quotation marks
- [x] Above the Add button, 30 px
- [x] Above Footer, 60px margin top
- [x] remove the bottom margin of the button group (submit, clear form)
- [x] Below Section Intro, should be 30px
- [x] FormButtonGroup space between buttons should be 10px (remove inline block property of the buttons)
^ Create a DSR issue for the DS and then DSR - Destructive Action

**Comment by natalia-fitzgerald** [comment]
@shindigira 
The space under "Email" should be 10px. See: https://github.com/cfpb/sbl-frontend/pull/327#issuecomment-2026549957
