### ISSUE TITLE
Style mismatches and feature bugs - Part 2

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#398]
## Current behavior
- Global:
  - [x] Links in the footer are all 404’ing. Update links.
  - [x] Sigmund put in a fix in DSR that allows us to define the base URL for these links. 
  - [x] We just need to update the library and apply a base URL
- Page: View your user profile:
  - [ ] There's an extra 15px of space under the "Approved. Bank | LEI." The total space above and below should be 30px.
    - ** Result of explorations in #340, will make note there about broader impacts of those changes
  - [ ] For the "Approved Financial institution name | LEI (link)" I am looking at the approaches you posted to the issue and will also pitch a few alternatives so we can discuss.

**Comment by billhimmelsbach** [comment]
Closing this as we've gone through several pre-clearance design reviews
