### ISSUE TITLE
[Task][Styling][Filing Home] Squished centering and integrated Alerts

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#413]
<img width="1426" alt="Screenshot 2024-04-20 at 12 23 32 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/83fe661d-a6ca-4f37-901f-f0ac47a8cd50">

**Comment by billhimmelsbach** [comment]
Fixed via a number of design reviews on this page.
