### ISSUE TITLE
[Task][Bug] Handle the instance where user-fi instance is returning a 500 on initial load

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#429]
<img width="1028" alt="Screenshot 2024-04-29 at 8 55 57 AM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/d0a23280-b611-482f-b745-4084f631f4ca">

**Comment by billhimmelsbach** [comment]
Handled by the error boundary work.
