### ISSUE TITLE
[Accessibility] DSR Tables

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#462]
Test using [VoiceOver](https://support.apple.com/guide/voiceover/turn-voiceover-on-or-off-vo2682/mac#:~:text=Turn%20VoiceOver%20on%20or%20off%20at%20any,Press%20Command%2DF5.)/Talkback

" the columns numbers aren't lining up with what they actually are (check with screen reader)."

Pages
- [ ] Errors
- [ ] Warnings
  
ARIA properties
- `<table>` - [aria-colcount](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-colcount)
- `<td>` - [aria-colindex](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-colindex)

**Comment by billhimmelsbach** [comment]
It's the columns numbers that I think are the thing that's most noticeably off for me? Ping me when ya work on this @shindigira?

**Comment by meissadia** [comment]
Useful guide to WebAIM voiceover commands: https://webaim.org/articles/voiceover/

I am unable to replicate this issue in Safari with any tables on Errors/Warnings pages.  

All of the column numbers align with what I expect:
- On smaller tables (4 columns), the announced column numbers align (i.e. Column 2 of 4)
- On larger tables that scroll horizontally (10 columns), the announced column numbers align (i.e. Column 10 of 10)

**Comment by meissadia** [comment]
After reviewing with Bill, this doesn't seem to be an actual issue - column numbers *are* being correctly read - though the way screen readers announce the column count before the cell content (i.e. "Column 2 of 2, Unique identifier uid") could be confusing to users because it could be easily misinterpreted.

**Comment by meissadia** [comment]
Closing this issue per the comment above.
