### ISSUE TITLE
[Upload] Implement an Alert and body text to address SUBMISSION_ACCEPTED

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#467]
## Explanation
- The user clicked on the Warnings accepted confirmation -- status is now SUBMISSION_ACCEPTED -- but if the user goes back to upload there isn't a message to notify the user of this

**Comment by natalia-fitzgerald** [comment]
@shindigira 
I see two instances for SUBMISSION_ACCEPTED

### 1) User DOES NOT have warnings, clicks Save and continue on the Review warnings step
If this user returns to Upload file after backend: SUBMISSION_ACCEPTED they would see the same screen that they saw when they initially upload this file --> backend: VALIDATION_SUCCESSFUL
<img width="694" alt="Screenshot 2024-05-08 at 12 01 16 AM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/f4ac12ab-aff0-4352-9ecb-6317132d3119">

### 2) User DOES have warnings, clicks on the checkbox to verify warnings on the Review warnings steps
If this user returns to Upload file after backend: SUBMISSION_ACCEPTED the field level status alert for the validation check will be something like: "Your file contains no errors and warnings have been successfully verified"...Running by Angel and will post a screenshot once he's reviewed.
