### ISSUE TITLE
[Design] Enable `Save and continue` on all pages

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#491]
# Background info
Depending on the page, we currently 
  - disable the `Save and continue` button until the user has met the criteria to progress to the next step, or
  - enable the `Save and continue` button and check if the user is able to progress upon clicking of the button

With this change we would provide a more consistent experience:
- Show the `Save and continue` button as "enabled" on all pages
- When the user clicks `Save and continue`, we would then validate if they are able to progress
  - If not
    - Prevent user from progressing to the next step
    - show in-line errors for fields that
      - are required but not populated
      - contain malformed data
    - Scroll to the alert/error
  - If so
    - move to the next step

# Phase 1
#549 
Implement this on pages: Upload, Errors, Warnings
  - We already have the logic there to disable the button if tasks are not complete, we will just need to repurpose that to instead adjust the `primary/secondary` type of the `Save` button instead of disabling it.

# Phase 2
#550 
Implement this on pages: Type of FI, Point of Contact
  - Show `Save` button as `secondary` by default
  - Run validation logic as the user fills out the forms
  - Only show validation errors if the validation has been triggered by form submission
  - Show `Save` button as `primary` once form content meets minimum requirements for submission

**Comment by natalia-fitzgerald** [comment]
@shindigira @meissadia 
I think we're all on the same page now but we will include a "Go back" button on all pages, including "Provide type of financial institution." This button will return a user to the previous page.

**Comment by billhimmelsbach** [comment]
I think we want to check Update your financial institution profile: not with the button language of "Save and continue" but allow users to always click the submit?

**Comment by billhimmelsbach** [comment]
I think is working on all filing app pages and [there's a ticket remaining](https://github.com/cfpb/sbl-frontend/issues/611) for a similar behavior for Update your financial institution profile.
