### ISSUE TITLE
Enable buttons for "Save and continue" 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-frontend#499]
To maximize accessibility and usability we will enable all "Save and continue" buttons within the filing process. If a user clicks "Save and continue" when the required actions for the step have not been completed the page will show a form-level error alert (top of the page) and, where applicable, a field-level error alert (under the field with missing information). This work is prioritized for post-clearance and prior to MVP beta release. 

## Current behavior
"Save and continue" disabled until required actions are completed for the step. 
<img width="498" alt="Screenshot 2024-05-15 at 12 27 46 AM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/acd178c4-5563-4f7a-8195-2071b1da05bf">

## Expected behavior
"Save and continue" enabled at all times. If user clicks on it without having completed the required actions form-level error alert appears at the top of the page, page jumps to the top of the alert (typical form validation behavior). 
<img width="500" alt="Screenshot 2024-05-15 at 12 27 05 AM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/4601f8ef-7194-4774-97a4-d9dde5139fdf">

**Comment by billhimmelsbach** [comment]
All set in the filing app, and [there's a remaining ticket](https://github.com/cfpb/sbl-frontend/issues/611) for Update your financial institution profile.
