### ISSUE TITLE
[Button] Secondary - Pipe color

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#510]
## Secondary button
- Update the color of the pipe character on the "Go back" button to match the rest of the button. It looks like it's currently getting a lighter blue.

<img width="561" alt="330653936-7f4d2049-955e-4f2b-9faf-fb5505d022c8" src="https://github.com/cfpb/sbl-frontend/assets/13324863/96220e1f-ea5f-4d1f-90bf-049d7392018c">

Context: https://github.com/cfpb/sbl-frontend/pull/430#issuecomment-2111513007

**Comment by billhimmelsbach** [comment]
Did you end up resolving this one with Natalia @shindigira?
