### ISSUE TITLE
[Design] [Review Warnings] Verify Accept - content update - Part 2

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#527]
<img width="504" alt="Screenshot 2024-05-15 at 3 47 46 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/ee638a23-718d-4fe1-81fd-329681efdcf3">

**Comment by meissadia** [comment]
Will be part of https://github.com/cfpb/sbl-frontend/issues/549

**Comment by meissadia** [comment]
Confirmed that this is implemented
