### ISSUE TITLE
[Design] Platform grid/header space alignment

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-frontend#529]
Opening this issue capture a mis-alignment I'm seeing between what's built in AWS, and what's in the page mock-ups and cf.gov. It appears that in development we have an extra 30px of width in the header space that should not be there. 

### consumerfinance.gov
- Content is contained within 1170px
- Max width is 1230px but only the hero spans/bleeds here
- All content, including the header space live within the 1170px wide space
<img width="1443" alt="Screenshot 2024-05-16 at 12 38 45 AM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/86b2680f-bf70-441d-9c0e-155c63897bf3">

### Page mock-ups (Figma):
- All content, including the header space (logo, navigation, etc.) live within the 1170px wide space
- Left edge of step indicator lines up with left edge of of logo and right edge of step indicator lines up with right edge of navigation links<img width="748" alt="Screenshot 2024-05-16 at 12 35 22 AM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/220cbdde-8a8b-4385-a8eb-1ea3d4991b36">

### Filing platform (AWS)
- Step indicator spans 1200
- Logo and navigation sit in a 1200px wide box 
- Navigation items are not right aligned within the width
<img width="1436" alt="Screenshot 2024-05-16 at 12 36 19 AM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/4466b237-c1fb-460b-9097-f20eae1f9858">

**Comment by meissadia** [comment]
@natalia-fitzgerald Please see the video in [this PR](https://github.com/cfpb/sbl-frontend/pull/640) which attempts to get the StepIndicator's responsiveness more closely aligned with the CFPB Header.
 
Note: The extra margin to the right of the `LOG OUT` button would need to be fixed in the DSR.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Yes, I flagged the issue with the DSR header component and the grid (separate ticket in DSR repo).

**Comment by meissadia** [comment]
I've updated https://github.com/cfpb/sbl-frontend/pull/640 with a better implementation that includes a fix for the `LOGOUT` button to be right-aligned and provides better break-point matching, so the top elements are now responsively aligned.
 
Regarding the 1200px max-width: This setting is coming from the Design System classes.  Looking at the DS code, this value *should be* `1170px`, and has been set to that value for at least the last two years, so even the fact that we're using an older version of the DS library (from Feb 2024) does not explain the mismatch.  I have been unable to determine why the coded value does not align with the calculated value.  
 
That said, we will eventually be upgrading to new BEM version of the DS library (v1+) so I think we should re-visit this issue then.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Can you create a ticket for the future work that will need to be done after we upgrade to the new BEM version of the DS library?
