### ISSUE TITLE
[Resolve Errors] [Review Warnings] Counts should be the number of rows affected by errors (or warnings)

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#538]
Currently, the count shows the amount of error (or warning) types found. It should be the number of rows affected by errors (or warnings)

<img width="1430" alt="Screenshot 2024-05-17 at 2 26 49 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/ba00fcf9-bdc4-4574-95a9-0b786f31a5a3">

**Comment by jcadam14** [comment]
This should be in the filing-api I believe?  Code is providing a count of error/warning codes (E3000, W0123, etc) and not the total record counts under each.
