### ISSUE TITLE
[Login] Implement Refresh Token handling (silent sign-in)

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#55]
#### Objectives
- [ ] See `auth.signinSilent` in [react-oidc-context](https://github.com/authts/react-oidc-context)
- [ ] Automatic Signin [implementation](https://github.com/cfpb/sbl-frontend/issues/25#issuecomment-1681077457)

**Comment by billhimmelsbach** [comment]
Closed by #751
