### ISSUE TITLE
(Phase 2) Enable Save and continue on all pages

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#550]
# Phase 1
#549 

# Phase 2
Implement this on pages: Type of FI, Point of Contact
  - Show `Save` button as `secondary` by default
  - Run validation logic as the user fills out the forms
  - Only show validation errors if the validation has been triggered by form submission
  - Show `Save` button as `primary` once form content meets minimum requirements for submission

**Comment by billhimmelsbach** [comment]
This was completed by #491
