### ISSUE TITLE
[Point of Contact] 'isDirty' is not functioning properly

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#555]
`isDirty` is not detecting state or territory changes. Will need to address

**Comment by meissadia** [comment]
@shindigira 

https://github.com/react-hook-form/react-hook-form/issues/4597#issuecomment-1069673930

PointOfContact > index.tsx
```
  const onSelectState = ({ value }: { value: string }): void => {
    setValue('hq_address_state', value, { shouldDirty: true });
  };
```
