### ISSUE TITLE
[Task] Pages that use grid are slightly differently aligned than ones that use the FormWrapper

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/sbl-frontend#579]
Pages that use grid are slightly differently aligned than ones that use the FormWrapper

## Current behavior

- Provide point of contact's spacing of the content wrapper on the page looks a little off for instance when compared to the other pages (ask @billhimmelsbach to show you)
![Screenshot 2024-05-24 at 5 07 58 AM](https://github.com/cfpb/sbl-frontend/assets/19983248/dfb405e3-9950-4bbc-931f-0da70024b7d0)
![Screenshot 2024-05-24 at 5 08 50 AM](https://github.com/cfpb/sbl-frontend/assets/19983248/36e0f23d-4f28-494f-88cf-af4623ad84f2)

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
Is the issue you're seeing related to this issue I flagged: https://github.com/cfpb/sbl-frontend/issues/529

**Comment by billhimmelsbach** [comment]
Duplicate of #529
