### ISSUE TITLE
[Resolve Errors] [Review Warnings] - Pagination - Responsive handling

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#626]
<img width="504" alt="Screenshot 2024-05-31 at 10 50 49 AM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/1db5b2df-0f7c-40ba-94c7-6c120626ff3d">

**Comment by billhimmelsbach** [comment]
Mind if I transfer this ticket to the DSR repo @shindigira?
