### ISSUE TITLE
[Alerts] Update on Resolve Errors + Warnings pages

### ISSUE THREAD

**Issue by ojbravo** [cfpb/sbl-frontend#865]
Update language and position of alerts on Resolve Errors and Warnings pages.

#### Mock-ups: 

**Resolve errors (syntax)**
<img width="453" alt="Screenshot 2024-08-08 at 4 55 10 PM" src="https://github.com/user-attachments/assets/598b9da2-b5b6-4eac-bc11-718eb38076f3">

**Resolve errors (logic)**
<img width="443" alt="Screenshot 2024-08-05 at 4 55 42 PM" src="https://github.com/user-attachments/assets/39849b92-b7ec-4d61-9c65-b4d0ddbfa368">

**Review warnings** 
This one replaces the existing field-level alert. 
<img width="426" alt="Screenshot 2024-08-05 at 4 55 51 PM" src="https://github.com/user-attachments/assets/d8eb9a43-eaa5-4d88-9942-7e94338e6881">

**Comment by ojbravo** [comment]
These are the actual screenshots:

Resolve errors (syntax):
<img width="523" alt="errorAlert-syntax" src="https://github.com/user-attachments/assets/7a388ba9-50ab-497e-bb32-c6b9cd5401b3">

Resolve errors (logic):
<img width="610" alt="errorAlert-logic" src="https://github.com/user-attachments/assets/d0447c0b-7745-4452-9c1b-222c55fb8a6b">

Review Warnings: 
<img width="849" alt="errorAlert-warnings" src="https://github.com/user-attachments/assets/a61abbfb-ec2f-4abd-8195-d7711208a039">

**Comment by natalia-fitzgerald** [comment]
@ojbravo 
Can you double check that the text in these messages is styled as paragraph text (16px, Regular weight) and not H4? It looks correct in the first set of screenshots but in the second one it looks like it changed to H4?

**Comment by ojbravo** [comment]
> @ojbravo Can you double check that the text in these messages is styled as paragraph text (16px, Regular weight) and not H4? It looks correct in the first set of screenshots but in the second one it looks like it changed to H4?

At present, the DSR <Alert /> component defaults to 'h4' and only allows h1 - h6. I've created a ticket in the DSR to allow for non-headings: https://github.com/cfpb/design-system-react/issues/378
