### ISSUE TITLE
[e2e] Failing tests

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#987]
### What I see running Playwright with 1 worker, after starting clean
<img width="373" alt="playwright-1-worker-mdia" src="https://github.com/user-attachments/assets/14121367-efb4-4622-ac6a-a90ed53927d1">

### Attempted fixes
- [x] Re-install Chromium

## Screenshots
- [x] Unavailable APIs
  - https://github.com/cfpb/sbl-frontend/pull/1004
- [x] Unauthenticated homepage - CFPB logo link
  <img width="1842" alt="Unauthenticated homepage - CFPB logo link" src="https://github.com/user-attachments/assets/acf00c51-5580-4817-8dd6-ec37f8a3ac86">

- [x] Navigation
  <img width="1842" alt="Navigation" src="https://github.com/user-attachments/assets/184bd854-2eb8-460c-8d33-cab2a97fa07a">

- [x] Institution Profile Page
  <img width="1842" alt="Institution Profile Page" src="https://github.com/user-attachments/assets/cf5ae540-ffb2-4891-ae65-8ed1085f031a">

**Comment by billhimmelsbach** [comment]
Related to: https://github.com/cfpb/sbl-project/issues/283
